apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{.Iteration}}-{{.Replica}}
  labels:
    apf: stress # static label so the read job can select these regardless of run uuid
data:
  payload: "prewarm"
